# An example of pushing XML events generated by the low-level expat
# XML library into coroutines.


import xml.parsers.expat


def expat_parse(file_object, target):
    parser = xml.parsers.expat.ParserCreate()
    parser.buffer_size = 65536
    parser.buffer_text = True
    # parser.returns_unicode = False
    parser.StartElementHandler = lambda name, attrs: target.send(('start', (name, attrs)))
    parser.EndElementHandler = lambda name: target.send(('end', name))
    parser.CharacterDataHandler = lambda data: target.send(('text', data))
    parser.ParseFile(file_object)


if __name__ == '__main__':
    from buses import *

    expat_parse(open("tiny_routes.xml", mode='rb'), buses_to_dicts(bus_locations()))
